/**
 * Builds the extension:
 * `node scripts/build.ts --mode production|development|qa [--watch] [--out-dir <dir>]`.
 * Output: `dist/` (prod, the store package), `dist-dev/` (dev) or `dist-qa/`
 * (prod bundle + the store item's `key`), loadable with "Load unpacked".
 * `--out-dir` builds elsewhere (e.g. a temp folder to check prod when `dist/`
 * is locked); relative paths are resolved against `extension/`. The folder is
 * wiped first, so it is restricted (see `assertSafeOutDir`).
 *
 * Runs with Node's built-in TypeScript type stripping (Node >= 22.18).
 */
import { cpSync, existsSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { isAbsolute, join, relative, resolve, sep } from 'node:path';
import { build } from 'vite';
import { ROOT, missingFirebaseValues, outDirOf, resolveBuildConfig, type BuildTarget } from '../build/common.ts';
import { BACKGROUND_FILE, CONSENT_FILE, CONTENT_FILE, DEV_EXTENSION_ID, ICONS, POPUP_FILE } from '../build/manifest.ts';
import { PARTS, partConfig } from '../build/parts.ts';
import { STORE_EXTENSION_ID, STORE_PUBLIC_KEY, extensionIdFromKey } from '../build/store-key.ts';

const TARGETS: Record<string, BuildTarget> = { production: 'prod', development: 'dev', qa: 'qa' };

const args = process.argv.slice(2);
const argOf = (name: string): string | undefined => {
  const i = args.indexOf(name);
  return i >= 0 ? (args[i + 1] ?? '') : undefined;
};
const mode = argOf('--mode') ?? 'production';
const target = TARGETS[mode];
if (!target) fail(`Modo inválido "${mode}" (usa production, development o qa).`);
const watch = args.includes('--watch');
const outDirArg = argOf('--out-dir');
if (outDirArg !== undefined && (outDirArg.trim() === '' || outDirArg.startsWith('--'))) {
  fail('--out-dir necesita una carpeta (p. ej. --out-dir dist-prueba).');
}
const outDir = resolve(ROOT, outDirArg ?? outDirOf(target));
assertSafeOutDir(outDir);

if (target === 'qa') checkQaConfig();

rmSync(outDir, { recursive: true, force: true });

for (const part of PARTS) {
  const config = partConfig(part, target, outDir);
  if (watch) config.build = { ...config.build, watch: {} };
  await build(config);
}
// Toolbar icons (static PNGs generated by scripts/icons.ts).
cpSync(join(ROOT, 'icons'), join(outDir, 'icons'), { recursive: true });

if (watch) {
  console.log(`Vigilando cambios → ${outDir}`);
} else {
  const id = checkBundle();
  console.log(`Extensión (${mode}) generada en ${outDir}`);
  if (id) console.log(`ID de la extensión: ${id}`);
}

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

/** `child` is strictly inside `parent` (case-insensitive on Windows, via `relative`). */
function isInside(child: string, parent: string): boolean {
  const rel = relative(parent, child);
  return rel !== '' && rel !== '..' && !rel.startsWith(`..${sep}`) && !isAbsolute(rel);
}

/**
 * The output folder is wiped before building, so `--out-dir` must not point at
 * anything that is not (or was not) an extension build:
 * - never `extension/` itself nor one of its parents (repo root, disk root…);
 * - inside the repo, only a direct child of `extension/` named `dist*`
 *   (`dist`, `dist-qa`, `dist-prueba`…), never `src/`, `packages/`, `portal/`…;
 * - anywhere else, only a folder that does not exist, is empty, or holds a
 *   previous build of this extension (its `manifest.json`).
 */
function assertSafeOutDir(dir: string): void {
  const repo = resolve(ROOT, '..');
  const bad = (why: string): never => fail(`--out-dir inválido (${why}): ${dir}`);
  if (relative(dir, ROOT) === '' || isInside(ROOT, dir)) bad('es extension/ o una carpeta que la contiene');
  if (relative(dir, repo) === '' || isInside(dir, repo)) {
    const rel = relative(ROOT, dir);
    if (!isInside(dir, ROOT) || rel.includes(sep) || !/^dist/i.test(rel)) {
      bad('dentro del repo solo se permite extension/dist*');
    }
  }
  if (!existsSync(dir)) return;
  if (!statSync(dir).isDirectory()) bad('no es una carpeta');
  if (readdirSync(dir).length === 0) return;
  let name = '';
  try {
    name = (JSON.parse(readFileSync(join(dir, 'manifest.json'), 'utf8')) as { name?: unknown }).name as string;
  } catch {
    // No manifest (or unreadable): not a previous build.
  }
  if (typeof name !== 'string' || !name.startsWith('Registro de jornada')) {
    bad('la carpeta tiene archivos y no es un build anterior de la extensión; usa una carpeta nueva o vacía');
  }
}

/**
 * QA is only useful with login against production: missing Firebase values,
 * OAuth client ID or web client ID (other browsers) are an error here (prod
 * only warns), and the store key must still yield the store item's ID.
 */
function checkQaConfig(): void {
  const derived = extensionIdFromKey(STORE_PUBLIC_KEY);
  if (derived !== STORE_EXTENSION_ID) {
    fail(`La clave de build/store-key.ts da el ID ${derived}, no el de la tienda (${STORE_EXTENSION_ID}).`);
  }
  const cfg = resolveBuildConfig('qa');
  const missing = missingFirebaseValues(cfg);
  if (!cfg.oauthClientId) missing.push('VITE_OAUTH_CLIENT_ID');
  if (!cfg.googleWebClientId) missing.push('VITE_GOOGLE_WEB_CLIENT_ID');
  if (missing.length > 0) {
    fail(
      `Build QA cancelado: faltan valores reales en .env.production / .env.production.local (${missing.join(', ')}). ` +
        'Sin ellos el login con Google contra producción no funciona. Ver extension/README.md.',
    );
  }
}

/**
 * The prod (and QA) bundle must not carry the dev login, the debug hooks nor the
 * emulator wiring: they sit behind `__APP_ENV__ === 'dev'`, which Vite
 * replaces literally and the minifier drops.
 */
function devLeftovers(): string[] {
  const FORBIDDEN = ['auth.devSignIn', 'debug.forcePulse', 'debug.forceScreenshot', 'Entrar (emulador)', 'email_verified', '127.0.0.1'];
  const found: string[] = [];
  for (const f of readdirSync(outDir, { recursive: true, encoding: 'utf8' })) {
    if (!/\.(js|html)$/.test(f)) continue;
    const text = readFileSync(join(outDir, f), 'utf8');
    for (const s of FORBIDDEN) if (text.includes(s)) found.push(`${f} contiene código dev ("${s}")`);
  }
  return found;
}

/** `key` rules of each target; returns the resulting extension ID (if pinned). */
function manifestProblems(problems: string[]): string | undefined {
  const manifest = JSON.parse(readFileSync(join(outDir, 'manifest.json'), 'utf8')) as chrome.runtime.ManifestV3;
  const id = manifest.key ? extensionIdFromKey(manifest.key) : undefined;
  switch (target) {
    case 'prod':
      // Chrome Web Store rejects packages whose manifest has `key`.
      if (manifest.key) problems.push('manifest.json del build prod tiene "key" (Chrome Web Store lo rechaza)');
      break;
    case 'qa':
      if (manifest.key !== STORE_PUBLIC_KEY || id !== STORE_EXTENSION_ID) {
        problems.push(`manifest.json de QA sin la key de la tienda (ID ${id ?? 'sin key'} ≠ ${STORE_EXTENSION_ID})`);
      }
      if (!manifest.oauth2?.client_id) problems.push('manifest.json de QA sin oauth2.client_id');
      break;
    case 'dev':
      if (id !== DEV_EXTENSION_ID) problems.push(`manifest.json dev con ID ${id ?? 'sin key'} ≠ ${DEV_EXTENSION_ID}`);
      break;
  }
  return id;
}

/** Guards against output that Chrome would refuse to run. */
function checkBundle(): string | undefined {
  const problems: string[] = [];
  const iconsOn = Object.values(ICONS).map((p) => p.replace('icon-', 'icon-on-'));
  for (const f of [BACKGROUND_FILE, CONTENT_FILE, POPUP_FILE, CONSENT_FILE, 'manifest.json', ...Object.values(ICONS), ...iconsOn]) {
    if (!existsSync(join(outDir, f))) problems.push(`falta ${f}`);
  }
  const bg = readFileSync(join(outDir, BACKGROUND_FILE), 'utf8');
  // Service workers reject dynamic import() at runtime.
  if (/\bimport\s*\(/.test(bg)) problems.push(`${BACKGROUND_FILE} contiene import() dinámico`);
  const content = readFileSync(join(outDir, CONTENT_FILE), 'utf8');
  // Content scripts are classic scripts: no ESM syntax.
  if (/^\s*(import|export)\s/m.test(content)) problems.push(`${CONTENT_FILE} contiene sintaxis ESM`);
  if (target !== 'dev') problems.push(...devLeftovers());
  const id = existsSync(join(outDir, 'manifest.json')) ? manifestProblems(problems) : undefined;
  if (problems.length > 0) fail(`Build inválido:\n - ${problems.join('\n - ')}`);
  return id;
}
