/**
 * Builds the extension: `node scripts/build.ts --mode production|development [--watch]`.
 * Output: `dist/` (prod) or `dist-dev/` (dev), loadable with "Load unpacked".
 *
 * Runs with Node's built-in TypeScript type stripping (Node >= 22.18).
 */
import { cpSync, existsSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { build } from 'vite';
import { ROOT, outDirOf } from '../build/common.ts';
import { BACKGROUND_FILE, CONSENT_FILE, CONTENT_FILE, ICONS, POPUP_FILE } from '../build/manifest.ts';
import { PARTS, partConfig } from '../build/parts.ts';

const args = process.argv.slice(2);
const modeIdx = args.indexOf('--mode');
const mode = modeIdx >= 0 ? (args[modeIdx + 1] ?? '') : 'production';
if (mode !== 'production' && mode !== 'development') {
  console.error(`Modo inválido "${mode}" (usa production o development).`);
  process.exit(1);
}
const watch = args.includes('--watch');
const outDir = join(ROOT, outDirOf(mode));

rmSync(outDir, { recursive: true, force: true });

for (const part of PARTS) {
  const config = partConfig(part, mode);
  if (watch) config.build = { ...config.build, watch: {} };
  await build(config);
}
// Toolbar icons (static PNGs generated by scripts/icons.ts).
cpSync(join(ROOT, 'icons'), join(outDir, 'icons'), { recursive: true });

if (watch) {
  console.log(`Vigilando cambios → ${outDir}`);
} else {
  checkBundle();
  console.log(`Extensión (${mode}) generada en ${outDir}`);
}

/**
 * The prod bundle must not carry the dev login, the debug hooks nor the
 * emulator wiring: they sit behind `__APP_ENV__ === 'dev'`, which Vite
 * replaces literally and the minifier drops.
 */
function devLeftovers(): string[] {
  const FORBIDDEN = ['auth.devSignIn', 'debug.forcePulse', 'debug.forceScreenshot', 'Entrar (emulador)', 'email_verified', '127.0.0.1'];
  const found: string[] = [];
  for (const f of readdirSync(outDir, { recursive: true, encoding: 'utf8' })) {
    if (!/\.(js|html)$/.test(f)) continue;
    const text = readFileSync(join(outDir, f), 'utf8');
    for (const s of FORBIDDEN) if (text.includes(s)) found.push(`${f} contiene código dev ("${s}")`);
  }
  return found;
}

/** Guards against output that Chrome would refuse to run. */
function checkBundle(): void {
  const problems: string[] = [];
  const iconsOn = Object.values(ICONS).map((p) => p.replace('icon-', 'icon-on-'));
  for (const f of [BACKGROUND_FILE, CONTENT_FILE, POPUP_FILE, CONSENT_FILE, 'manifest.json', ...Object.values(ICONS), ...iconsOn]) {
    if (!existsSync(join(outDir, f))) problems.push(`falta ${f}`);
  }
  const bg = readFileSync(join(outDir, BACKGROUND_FILE), 'utf8');
  // Service workers reject dynamic import() at runtime.
  if (/\bimport\s*\(/.test(bg)) problems.push(`${BACKGROUND_FILE} contiene import() dinámico`);
  const content = readFileSync(join(outDir, CONTENT_FILE), 'utf8');
  // Content scripts are classic scripts: no ESM syntax.
  if (/^\s*(import|export)\s/m.test(content)) problems.push(`${CONTENT_FILE} contiene sintaxis ESM`);
  if (mode === 'production') problems.push(...devLeftovers());
  if (problems.length > 0) {
    console.error(`Build inválido:\n - ${problems.join('\n - ')}`);
    process.exit(1);
  }
}
